services:
  px4:
    platform: linux/amd64
    image: px4io/px4-dev-simulation-jammy:latest
    container_name: px4_sitl
    volumes:
      - ../px4/PX4-Autopilot:/px4
    stdin_open: true
    tty: true
    command: bash -lc "sleep infinity"
