# CI workflow for Aquila project

# Necessary steps:
    # Checkout repo
    # Install C++/CMake
    # Set up Python and install sim requirements
    # Configure + build C++ with CMake
    # Run ctest
    # Run pytest sim/tests

name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sim/requirements.txt

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build 
        run: cmake --build build --config Release

      - name: Run C++ Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Run Python Tests
        env:
            PYTHONPATH: .
        run: pytest sim/tests